[package]
name = "mail-auth"
version = "0.1.0"
edition = "2021"


[dependencies]
#mail-parser = { version = "0.7", git = "https://github.com/stalwartlabs/mail-parser", features = ["ludicrous_mode", "full_encoding"] 
mail-parser = { path = "/home/vagrant/code/mail-parser", features = ["ludicrous_mode", "full_encoding"] }
mail-builder = { version = "0.2.4", git = "https://github.com/stalwartlabs/mail-builder", features = ["ludicrous_mode"] } 
rsa = {version = "0.7.0"}
ed25519-dalek = "1.0.1"
sha1 = {version = "0.10", features = ["oid"]}
sha2 = {version = "0.10.6", features = ["oid"]}
trust-dns-resolver = { version = "0.22.0", features = ["dns-over-rustls"] }
lru-cache = "0.1.2"
parking_lot = "0.12.0"
ahash = "0.8.0"
quick-xml = "0.26.0"

[dev-dependencies]
tokio = { version = "1.16", features = ["net", "io-util", "time", "rt-multi-thread", "macros"] }
